# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FortuneSlotWinRicobet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FortuneSlotWinRicobet
  pod 'Firebase/Messaging'
  pod 'AppsFlyerFramework'
  pod 'FBSDKCoreKit', '17.4.0'
  pod 'IQKeyboardManagerSwift'

end
